ego_rrt:
  ros__parameters:
    waypoints_path: "/sim_ws/src/pure_pursuit/racelines/e7_floor5_square.csv" 
    waypoints_path_2nd: "/sim_ws/src/pure_pursuit/racelines/e7_floor5.csv"
    scan_topic: "/scan"
    odom_topic: "/ego_racecar/odom"
    drive_topic: "/drive"

    lane_number: 0

    segments: 0 # 0 means do not do interpolation
    velocity_percentage: 1.0

    K_p: 0.5 
    K_p_obstacle: 0.8

    # normalized the lookahead
    min_lookahead: 1.0 # for larger track
    max_lookahead: 3.0 # lookahead when the car is going around max velocity
    min_lookahead_speed: 3.0
    max_lookahead_speed: 6.0 # approximately the max velocity
    
    # For when there is an obstacle
    velocity_min: 1.0
    velocity_max: 2.0
    steering_limit: 25.0
    cells_per_meter: 20 # map resolution is usually 0.05m/cell, so this makes sense

opp_rrt:
  ros__parameters:
    waypoints_path: "/sim_ws/src/pure_pursuit/racelines/e7_floor5_square.csv" 
    waypoints_path_2nd: "/sim_ws/src/pure_pursuit/racelines/e7_floor5.csv"
    scan_topic: "/opp_scan"
    odom_topic: "/opp_racecar/odom"
    drive_topic: "/opp_drive"

    rviz_current_waypoint_topic: "/opp_current_waypoint"
    rviz_lookahead_waypoint_topic: "/opp_lookahead_waypoint"
    rrt_path_topic: "/opp_rrt_path"
    rrt_node_array_topic: "/opp_rrt_node_array"
    occupancy_grid_topic: "/opp_occupancy_grid"
    velocity_percentage: 0.8

    K_p: 0.5
    velocity_min: 1.0
    velocity_max: 3.0
    steering_limit: 25.0
    cells_per_meter: 10


waypoint_visualiser_node:
  ros__parameters:
    waypoints_path: "/sim_ws/src/pure_pursuit/racelines/e7_floor5_square.csv" 
